### ISSUE TITLE
Fix failure when some resource in not available or enhance with whitelist

### ISSUE THREAD

**Issue by lashchanka** [bahmutov/cyclope#63]
In case you have part of resources unavailable (missing image e.g.) the plugin will fail with this error:

![image](https://user-images.githubusercontent.com/81577230/175968819-e34664b1-2c0b-4e44-8bdc-192ae7115d71.png)

This issue has at least 2 negative sides:
-  You can't use plugin in your project, sometimes you are not able to fix the bugs on your own, so you have to avoid `cyclope` at all
-  Any bug with 404 error will break the plugin [here](https://github.com/bahmutov/cyclope/blob/main/plugin/index.js#L19)

A proposal here can be to add some glob pattern ignore list, so if the resource is unavailable, we can simply skip it:

```ts
require('cyclope/plugin')(on, config, {
      ignoreFailed: ['assets/**/*.png'],
  });
```

In case you wan't to ignore all failures:
```ts
require('cyclope/plugin')(on, config, {
      ignoreFailed: true,
  });
```

@bahmutov could you extend the plugin, please?

Thanks in advance 🙇

**Comment by bahmutov** [comment]
it would be a new feature, I guess I see why it is needed though

**Comment by lashchanka** [comment]
@bahmutov please, check PR to partially cover the request:
https://github.com/bahmutov/cyclope/pull/64
