### ISSUE TITLE
savePageIfTestFailed on cypress 10

### ISSUE THREAD

**Issue by jomarko** [bahmutov/cyclope#74]
I struggle to finish `savePageIfTestFailed` using cypress ten, especially the snippet for `support/index.js` causes an issue:
```
import { savePageIfTestFailed } from 'cyclope'
afterEach(savePageIfTestFailed)
```

The `import from` causes this error:
```
File '/home/jomarko/redhat/smart-events/sandbox-ui/node_modules/cyclope/src/index.d.ts' is not a module.ts(2306)
```

Do you have any suggestion how to setup `cyclope` for cypress 10 project?

**Comment by bahmutov** [comment]
Yes, add ts-ignore comment

```
// @ts-ignore
import { savePageIfTestFailed } from 'cyclope'
```
